spring:
  datasource:
    url: 'jdbc:postgresql://localhost:54321/postgres'
    username: 'postgres'
    password: 'admin'
    driver-class-name: 'org.postgresql.Driver'

  flyway:
    locations: 'classpath:db'

server:
  port: 8000

