spring:
  datasource:
    url: 'jdbc:postgresql://localhost:54321/postgres'
    username: 'postgres'
    password: 'admin'
    driver-class-name: 'org.postgresql.Driver'

  flyway:
    locations: 'classpath:db'

server:
  port: 8000
  servlet:
    context-path: /api

application:
  security:
    jwt:
      secret-key: 97b1daf8ee0ee7c99b0e2271ac621c4e2d8c98fb3f65b1fa8f489e988e49f610